# Generated by Django 5.1 on 2024-10-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=50)),
                ('primary_instructor', models.CharField(max_length=255)),
                ('course_code_new', models.CharField(max_length=50)),
                ('department_code', models.CharField(max_length=50)),
                ('core_code', models.CharField(max_length=50)),
                ('course_group', models.CharField(max_length=50)),
                ('grade', models.IntegerField()),
                ('class_group', models.CharField(max_length=50)),
                ('course_name_cn', models.CharField(max_length=255)),
                ('course_name_en', models.CharField(max_length=255)),
                ('instructor_name', models.CharField(max_length=255)),
                ('enrollment', models.IntegerField()),
                ('male_students', models.IntegerField()),
                ('female_students', models.IntegerField()),
                ('credits', models.IntegerField()),
                ('weeks', models.IntegerField()),
                ('hours_per_week', models.FloatField()),
                ('course_type_code', models.CharField(max_length=50)),
                ('course_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('weekday', models.CharField(max_length=20)),
                ('class_period', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('course_summary_cn', models.TextField(blank=True, null=True)),
                ('course_summary_en', models.TextField(blank=True, null=True)),
                ('primary_instructor_code_old', models.CharField(max_length=50)),
                ('course_code_old', models.CharField(max_length=50)),
                ('schedule_code_old', models.CharField(max_length=50)),
                ('schedule_name_old', models.CharField(max_length=100)),
                ('instructor_code_old', models.CharField(max_length=50)),
            ],
        ),
    ]
